"""empty message

Revision ID: 182e20a277d
Revises: 3abbccb2d8f
Create Date: 2015-07-22 22:22:48.926550

"""

# revision identifiers, used by Alembic.
revision = '182e20a277d'
down_revision = '3abbccb2d8f'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=True),
    sa.Column('start', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('end', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sqlalchemy_utils.types.scalar_list.ScalarListType(float), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bar_events')
    op.drop_table('notifications')
    ### end Alembic commands ###
