"""empty message

Revision ID: 2e0efb4721e
Revises: None
Create Date: 2015-07-21 13:26:34.822411

"""

# revision identifiers, used by Alembic.
revision = '2e0efb4721e'
down_revision = None

from alembic import op
from serveza.settings import PASSWORD_SCHEMES
import serveza.db
import sqlalchemy_utils
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('brewery', sa.Unicode(), nullable=True),
    sa.Column('degree', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(schemes=PASSWORD_SCHEMES), nullable=True),
    sa.Column('api_token', sa.String(length=32), nullable=True),
    sa.Column('avatar', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bar_beers',
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('price', serveza.db.MoneyType(), nullable=True),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.PrimaryKeyConstraint('bar_id', 'beer_id')
    )
    op.create_table('bar_owners',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bar_id')
    )
    op.create_table('user_beers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'beer_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_beers')
    op.drop_table('bar_owners')
    op.drop_table('bar_beers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('beers')
    op.drop_table('bars')
    ### end Alembic commands ###
