"""Add favorited beers and bars

Revision ID: 379a369c64e
Revises: 2d7048d80ce
Create Date: 2015-07-25 22:58:31.392151

"""

# revision identifiers, used by Alembic.
revision = '379a369c64e'
down_revision = '2d7048d80ce'

from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bars',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bar_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bars')
    ### end Alembic commands ###
