"""empty message

Revision ID: 3abbccb2d8f
Revises: 2e0efb4721e
Create Date: 2015-07-22 21:35:28.681000

"""

# revision identifiers, used by Alembic.
revision = '3abbccb2d8f'
down_revision = '2e0efb4721e'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bars', sa.Column('website', sqlalchemy_utils.types.url.URLType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bars', 'website')
    ### end Alembic commands ###
