"""Add user last_event_check

Revision ID: a7a2780295
Revises: 182e20a277d
Create Date: 2015-07-22 22:31:21.123967

"""

# revision identifiers, used by Alembic.
revision = 'a7a2780295'
down_revision = '182e20a277d'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_event_check', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_event_check')
    ### end Alembic commands ###
